# Generated by Django 2.1.3 on 2019-07-05 10:41

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.CharField(max_length=1000)),
                ('comment_date', models.DateField(auto_now_add=True)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commment_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Journalism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(max_length=150)),
                ('draft_date', models.DateTimeField(auto_now_add=True)),
                ('number_of_views', models.IntegerField(default=0)),
                ('claps', models.IntegerField(default=0)),
                ('ranking_determination', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='journalism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalisms', to='cms.Journalism'),
        ),
        migrations.AddField(
            model_name='comment',
            name='thump_down',
            field=models.ManyToManyField(blank=True, related_name='user_downvote_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='thump_up',
            field=models.ManyToManyField(blank=True, related_name='user_upvote_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
