# Generated by Django 2.1.3 on 2019-07-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalism',
            name='hidden_status',
            field=models.BooleanField(default=False),
        ),
    ]
