# Generated by Django 2.1.3 on 2019-05-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_journalism_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalism',
            name='post_status',
            field=models.CharField(blank=True, choices=[('p', 'Publish'), ('d', 'Draft')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='journalism',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalism',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
