# Generated by Django 2.1.3 on 2019-07-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_journalism_hidden_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_author',
            new_name='author',
        ),
    ]
