# Generated by Django 2.1.3 on 2019-08-13 12:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20190722_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_body',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='journalism',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
