# Generated by Django 2.1.3 on 2019-08-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20190813_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalism',
            old_name='draft_date',
            new_name='created',
        ),
    ]
