# Generated by Django 2.1.3 on 2019-05-13 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0005_auto_20190505_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.CharField(max_length=1000)),
                ('thump_up', models.PositiveIntegerField(blank=True, null=True)),
                ('thump_down', models.PositiveIntegerField(blank=True, null=True)),
                ('comment_date', models.DateField()),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=1000)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='cms.Comment')),
                ('respondent', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThumpDownData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thump_value', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('related_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_down', to='cms.Comment')),
                ('who_thump_down_comment', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThumpUpData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_thump_up_comment', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('thump_up_value', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('related_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Comment')),
            ],
        ),
        migrations.AlterField(
            model_name='journalism',
            name='draft_date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalisms', to='cms.Journalism'),
        ),
    ]
