# Generated by Django 2.1.3 on 2019-05-20 09:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0008_auto_20190513_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumpdowndata',
            name='related_comment',
        ),
        migrations.RemoveField(
            model_name='thumpdowndata',
            name='who_thump_down_comment',
        ),
        migrations.RemoveField(
            model_name='thumpupdata',
            name='related_comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commment_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='thump_down',
        ),
        migrations.AddField(
            model_name='comment',
            name='thump_down',
            field=models.ManyToManyField(blank=True, related_name='user_downvote_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='thump_up',
        ),
        migrations.AddField(
            model_name='comment',
            name='thump_up',
            field=models.ManyToManyField(blank=True, related_name='user_upvote_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='respondent',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalism',
            name='post_status',
            field=models.CharField(blank=True, choices=[('p', 'Publish'), ('d', 'Draft')], default='d', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='journalism',
            name='published_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2019, 5, 20, 9, 54, 47, 608959, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='ThumpDownData',
        ),
        migrations.DeleteModel(
            name='ThumpUpData',
        ),
    ]
