# Generated by Django 2.1.3 on 2019-05-20 10:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20190520_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalism',
            name='draft_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 20, 10, 23, 36, 6478, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='journalism',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
