# Generated by Django 2.1.3 on 2019-05-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20190520_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalism',
            name='draft_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
