# Generated by Django 2.1.3 on 2019-05-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20190531_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalism',
            name='claps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='journalism',
            name='number_of_views',
            field=models.IntegerField(default=0),
        ),
    ]
