# Generated by Django 2.1.3 on 2019-06-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_journalism_ranking_determination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='respondent',
        ),
        migrations.RemoveField(
            model_name='journalism',
            name='post_status',
        ),
        migrations.RemoveField(
            model_name='journalism',
            name='published_date',
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
