# Generated by Django 2.1.3 on 2019-04-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('picture', models.ImageField(upload_to='post_image')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_image')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Your post title', max_length=40)),
                ('body', models.CharField(max_length=1000)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('opportunity', 'Opportunity'), ('business_hub', 'Business Hub'), ('admission', 'Admission'), ('politics', 'Politics'), ('award', 'Awards'), ('relationship', 'Relationship'), ('events', 'Events'), ('knowledge', 'Knowledge'), ('creative_writing', 'Creative Writing'), ('general', 'General')], max_length=20)),
                ('view_number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
