# Generated by Django 2.1.3 on 2019-08-13 12:00

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_auto_20190711_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment_reply_hidden', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='thumped_down',
            new_name='comment_thumped_down',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='thumped_up',
            new_name='comment_thumped_up',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumped_down',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumped_up',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_array_flag_comment',
            field=models.ManyToManyField(related_name='comment_user_flag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='post_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='post_thumped_down',
            field=models.ManyToManyField(related_name='thumped_down_actors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='post_thumped_up',
            field=models.ManyToManyField(related_name='thumped_up_actors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user_array_flag_post',
            field=models.ManyToManyField(related_name='post_user_flag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='commentpicture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='forum_comment_image'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_pictures', to='forum.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('opportunity', 'Opportunity'), ('business_hub', 'Business Hub'), ('admission', 'Admission'), ('politics', 'Politics'), ('award_competition', 'Awards and Competition'), ('relationship', 'Relationship'), ('social_life', 'Campus Social Life'), ('creative_writing', 'Creative Writing'), ('general', 'General'), ('youth_service', 'Youth Service')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.Comment'),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='reply_thumped_down',
            field=models.ManyToManyField(related_name='replies_thumped_down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='reply_thumped_up',
            field=models.ManyToManyField(related_name='replies_thumped_up', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='user_array_flag_comment_reply',
            field=models.ManyToManyField(related_name='reply_flag', to=settings.AUTH_USER_MODEL),
        ),
    ]
