# Generated by Django 2.1.3 on 2019-04-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='starting',
            field=models.DateField(),
        ),
    ]
