# Generated by Django 2.1.3 on 2019-07-21 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action_verb', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_target_model', to='contenttypes.ContentType')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_perfomers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
