# Generated by Django 2.1.3 on 2019-07-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='is_comment_thump',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
