# Generated by Django 2.1.3 on 2019-07-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_picture',
            field=models.ImageField(default='/static/img/default_profile.png', upload_to='profile_picture'),
        ),
    ]
