# Generated by Django 2.1.3 on 2019-07-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190705_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='header_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_header'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/static/img/default_profile.png', null=True, upload_to='profile_picture'),
        ),
    ]
