# Generated by Django 2.1.3 on 2019-01-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('course_title', models.CharField(default='Politics in Africa', max_length=100)),
                ('course_code', models.CharField(default='POS 111', max_length=30)),
                ('material_title', models.CharField(blank=True, max_length=100, null=True)),
                ('shared_by', models.CharField(max_length=30, null=True)),
                ('review', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_download_course_material', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='coursematerial.CourseMaterial')),
            ],
        ),
        migrations.CreateModel(
            name='PastQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('course_code', models.CharField(default='POS 211', max_length=30)),
                ('course_title', models.CharField(default='Introduction to Sociology', max_length=100)),
                ('school', models.CharField(max_length=50, null=True)),
                ('download', models.IntegerField()),
                ('number_of_share', models.IntegerField()),
                ('review', models.TextField(default='This past question save my life!', max_length=100)),
                ('post_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('number_of_past_question_share', models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='coursematerial.PastQuestion')),
                ('number_of_course_material_shares', models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to='coursematerial.CourseMaterial')),
            ],
        ),
        migrations.AddField(
            model_name='download',
            name='number_of_download_past_question',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='question_number', to='coursematerial.PastQuestion'),
        ),
    ]
