# Generated by Django 2.1.3 on 2019-08-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursematerial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='fileupload',
            old_name='upload_time',
            new_name='created',
        ),
    ]
