# Generated by Django 2.1.3 on 2019-07-26 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumpednotification',
            name='is_comment_thump',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thumpednotification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='thumpednotification',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='thumpednotification',
            name='thumped_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumped_up_target', to='contenttypes.ContentType'),
        ),
    ]
